### ISSUE TITLE
Discussion: Encoding and serializiation

### ISSUE THREAD

**Issue by BearGuy** [SaitoTech/saito-rust#23]
Hey folks,

There has been some internal discussion about serialization and encoding, so I thought it would make sense to document some of the ideas in these discussions more publicly.

Rust gives quite a few methods to implement serialization, and currently there's a short list of the ones that have been discussed, each containing their own sets of pros and cons.

#### Pros
- Compact, fast byte encoding native to Rust and its type system
- Supported by other projects, including `google/tarpc` a Rust implementation of RPC that requires no additional tooling or languages to create a message schema.
- Easy to implement, plug and play with `Serde` using the `bincode` crate.
#### Cons
- Rust specific and tightly coupled, meaning almost no other language support
- Less control in encoding, potentially meaning less performant

#### Pros
- Platform and language neutral
- Easier to implement than building a custom serializer
#### Cons
- Additional complexity to manage a separate language
- Less efficient than custom serializer

#### Pros
- Complete control over encoding our structures, easy to optimize where we need it
#### Cons
- Cost of development time, maintenance, and bug fixing
- Would require recreating it for each new implementation in another language

There's a few other open-ended questions to factor into this conversation that will influence the decision. One of them in my mind is will the Rust version be the only version that is allowed to run consensus? If so, being as tightly coupled to Rust isn't as big of an issue.

Personally, at time of writing I'm leaning most towards Protocol buffers. It's a good compromise of dev complexity, language agnosticism, and efficiency that gives us decent flexibility moving forward.

If there are other standards that should be considered, please mention them! Now is the time to lay it out before anything gets implemented.

**Comment by escapedcat** [comment]
Yesterday I tried finding anything JS-library-ish that could handle rust-bincode. Just to see if there's something in that direction. Didn't find anything that looked hopeful. 

Also tagging @batzor here for maybe more feedback

**Comment by clayrab** [comment]
One big downside of protobufs is that the entire protobuf spec becomes part of our spec. The upside is we might get considerable performance benefits. 

I think bincode isn't a viable long-term solution.

"Would require recreating it for each new implementation in another language". I view this as a "pro" for custom serializers, not a con. The encoding scheme must be implementable in arbitrary languages.

**Comment by batzor** [comment]
I will just leave it here. https://gist.github.com/ilblackdragon/88ab377bf0da7ff721af80cb8a11fe28

**Comment by BearGuy** [comment]
Just though I'd mention, benchmarking and tests of these different solutions exist in the `serialization` branch here in this repo for anyone who's curious or wishes to help us extend testing.

**Comment by escapedcat** [comment]
Linking the mentioned branches:
- https://github.com/SaitoTech/saito-rust/tree/serialization_play
- https://github.com/SaitoTech/saito-rust/tree/serialization_test

**Comment by escapedcat** [comment]
Can this be closed?

**Comment by trevelyan** [comment]
Thank you for the discussion everyone!

We are implementing custom serialization at this point.
