### ISSUE TITLE
Keypair management UX

### ISSUE THREAD

**Issue by clayrab** [SaitoTech/saito-rust#39]
We have a keypair class that enables us to create keypairs, but the UX needs to be done.

Our vision is that users should be prompted to create a password encrypted keypair the first time they start a node which creates an encryted keypair file at a standard location.

If the keypair file already exists, the user should be prompted for the password.

The user should also be able to pass a command line argument with the path to another encryted keypair file(which should use the same password encrypting scheme and prompt them for a password also).

Another option might be to allow users to pass an unencrypted password file as a command line parameter, but this is I think just "nice to have". Could be done if it's very easy, but might also complicate UX significantly.

We're open to suggestions on changes to this design.

**Comment by escapedcat** [comment]
To hide passwords on input: https://stackoverflow.com/a/28926931/1667461

**Comment by escapedcat** [comment]
@clayrab can you describe where in the code this should be done?  
When should the rust code prompt for a password?
How will this be triggered?  
I'm interested to give this a try.

**Comment by clayrab** [comment]
It should figure all this out as soon as you run "cargo run" or "./saito_rust"(if you've built a binary).

If you do something like "./saito_rust --pw-file=/myencryptedusb/saitopw" then it should read from that, otherwise it should read from a standard location(maybe ./data/passwd?). If --pw-file isn't passed and the standard location is empty, then it should say something like "no password file found, creating one at ./data/passwd, please enter a password:".

So, in total the user should see one of three messages:

"Loading password from {location which user has provided}, please enter password:"
"Loading password from {standardize location on the system}, please enter password:"
"Password file not found, creating one at {standardize location on the system}, please enter password:"

I think that pretty much covers it... I'm open to ideas though.

**Comment by clayrab** [comment]
Right now we are just doing all resource sharing via the BLOCKCHAIN_GLOBAL global, so you can just create a file like keypairstore.rs and add a new() one in Blockchain struct the way we've done for utxoset, longest_chain_queue, and fork_tree.
