### ISSUE TITLE
First Wallet Implementation

### ISSUE THREAD

**Issue by BearGuy** [SaitoTech/saito-rust#40]
Once there are golden tickets #36 being produced in consensus, the system will start to have slips that will govern network functions.

Each node needs a way to collect and organize their slips, as well as create transactions with the proper slip balances to pay fees to the network. We'll want a `Wallet` struct that will be capable of doing this functionality.

The `Wallet` will need to contain:
- shared state that can safely be shared and accessed across multiple threads (`Arc` and `Rwlock`)
- A body that can be serialized
- Said body will need to contain important fields  such as 
  - Slip Array
  - Keypair
  - Balance
  - Pending slips in candidate block
  - Wallet Version
  - Default Fee when creating Transactions

The basic API we should support at first is
- `add_slip(slip: Slip)`
- `remove_slip(slip: Slip)`
- `create_transaction(fee: u64, amount: u64)`
- `create_signature(data: [u8; 32])`

A rough implementation can be found in the `master` branch of this repo.

**Comment by clayrab** [comment]
I'm not sure we want Pending Slips to be part of the Wallet namespace....

We also need a more sophisticated way of handling "wallet version" than what saito-lite does.

I think perhaps a node should be able to have multiple wallets which are stored separately, there's no reason to nuke an old wallet everytime someone generates a new keypair or we upgrade the wallet. Also, I think keypairs should be stored separately. i.e. someone should be able to store their keypair on a usb drive or pass in a private key on the command line, but the slips associated with that keypair should be stored by the node in a separate file structure which can also be transported, but separately from the keypair.

I think API should remove create_signature and the constructor of these should take a KeyPair:

new(keypair: KeyPair)
add_slip(slip: Slip)
remove_slip(slip: Slip)
create_transaction(...)

Perhaps another way to think about this is that we should just have a Slip Database(not an actually database) that just stores slips on disk but which can be accessed by a few methods like getSlipsFrom(pubkey), getSlipsTo(pubkey), getAllSlips(), etc and then we can have some command line functions that will help people to import/export keypairs and slips. e.g. saitorust --exportWalletFor=0xDEADBEEF01234 and saitorust --importWallet=myWalletFile.zip. So internally we have a namespace called "SlipDatabase" but only externally we call it "wallet". If we want to conceptualize things as a "wallet" internally, then I think it should support multiple keypairs at least, or if we want to think of a wallet as management for a single keypair then we need something like a WalletStore that holds multiple wallets.
