### ISSUE TITLE
add_block_to_blockchain 1/4 - Block Caching

### ISSUE THREAD

**Issue by BearGuy** [SaitoTech/saito-rust#41]
To extend adding blocks to the longest chain, we'll need to implement saving `Block`s to disk. We'll want a `Storage` module to easily read and write `Block`s.

As we're using `tokio`, the best way to do this would be to implement this asynchronously. We'll also want to extend some traits within `Block` to make it easy to swap out serialization, as we've yet to decide what serialization method we'll be implementing in the long term. For now, using bincode to serialize should be fine, as long as it's implemented in a trait and not hardcoded.

The functions we want to add are:
- `async read_block_from_disk(block_hash: [u8: 32]) -> Result<Block, Err>`
- `async write_block_to_disk(block: Block) -> Result<(), Err>`

A synchronous, rough implementation of `Storage` can be found in the `master` branch.

**Comment by clayrab** [comment]
I'm not sure what you mean by "implement this asynchronously". I think the way to think about this is like a cache with a TTL/Expiration policy. For version 1 we'd have something like a setTimeout which should expire the blocks from the cache/memory and then in the future the expire() method could perhaps also be called in a more sophisticated way(i.e. when the system becomes memory constrained).

With that mental model in mind, my intuition is that blocks should have an interface that lazy loads when you do get() and then automatically expires itself under some policy which is executed asynchronously. So there is some expire() method which is managed by the block itself for now, i.e. everytime the block is get()ed, we bump the TTL.

**Comment by clayrab** [comment]
I've renamed this to "Block Caching" and copied it into the project management board

**Comment by trevelyan** [comment]
closing as we are no longer using bincode to serialize.
