### ISSUE TITLE
Miner Module

### ISSUE THREAD

**Issue by BearGuy** [SaitoTech/saito-rust#42]
For now, to generate slips and get Saito circulating in the system, we auto generate `GoldenTicket` `Transaction`s and feed them into the `Mempool` where they're bundled and added to the chain.

We want a `Miner` module to do some mining work to generate these golden tickets. We want to port over the existing `Miner` from the `master` branch, remove the `Lottery` and `LotteryGame` cruft around it and add tests.

**Comment by clayrab** [comment]
I was speaking with Richard today about the viewpoint that hash difficultly on Saito is actually just a source of randomness and we were thinking that it would be interesting to have a few testnets that demonstrate this in various ways. E.G. we could have a testnet that simply uses the latest BTC block hash as a source of randomness and 100% of the Golden Chunk goes to Routers...

I'd like to see this flexibility reflected in the module interfaces so we can easily drop in different sources of randomness in the future...

I think I may have gave you some pushback to the term "lottery" at some point, but I'm actually coming around on that, but also perhaps it should be in it's own namespace/class?

**Comment by clayrab** [comment]
Was speaking to David. PoS vs PoW is a better excample of another type of "lotteryGame" we might want to swap in for another testnet or mainnet.

**Comment by trevelyan** [comment]
Miner module implemented, so closing!
