### ISSUE TITLE
Lottery Game Module

### ISSUE THREAD

**Issue by BearGuy** [SaitoTech/saito-rust#46]
After @clayrab pointed out in #42, we'll want a generic way to create randomness in golden ticket creation. Traditionally, we've used a SHA256 miner to achieve this, but we'll want some sort of interface for multiple lottery games to conform to outside of just mining.

The way to go about this is creating a trait called `LotteryGame` that exposes an interface that all Saito lottery games need to  conform to. A higher level struct called `Lottery` will control running the game, and will be used to initialize the `LotteryGame` when a node starts running.

**Comment by trevelyan** [comment]
Closing issue -- lets go with classic implementation for now.

No reason for more flexible implementation before we need it.
