### ISSUE TITLE
Serialization Benchmark Tooling

### ISSUE THREAD

**Issue by clayrab** [SaitoTech/saito-rust#51]
I want to create some tooling so that we can actually simulate creating a blockchain and then hitting it with incoming blocks and transactions and observe the behavior. If Cargo bench can do all this, I think we shoudl use that. Otherwise, maybe this should a separate crate under a tools lib that interacts with the node runtime via the system(e.g. through some socket)

**Comment by trevelyan** [comment]
Let me take a stab at some asynchronous functions that might help us do the same within "cargo test"
